language: node_js
node_js:
- 8
script:
- yarn --cwd app install
- yarn --cwd app build
- yarn --cwd admin install
- yarn --cwd admin build
- npm --prefix userapp install
- npm --prefix userapp run-script build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "$FIREBASE_SECURE_TOKEN"
  on:
    branch: master
env:
  global:
    secure: "cmPd183p1bnVgC0dnhjm/+VgigDQ1x52MA0RE3QXbJbB0kjr5QhXvAqmmiLDyeuMRSU001/JOE+zd3CRBxfe9EQAmVh2z3v8K5JeiPXERksZaaaSB8FmmJX36NQaDROS1CWupVC10gOmCZXtg6f2zJWlcL7ImdcPwN/DN79DlSejW7hBiRUaPkR4bcC5QbfOAo4+Lj/7Af0lWK6kfWm6lo084/E8nNVogViE2WgsHFQcE1m6j3XparAkJaUb99ovgAZT7C/QMGkPauc8OUK01UWnV2Ed0PqNKgDdZoXPSyacyzYfmQ8h/y06/opylpqpGglQkK6GNsD9s34SSmiH3Alg4XYaLL3SMxjqgb9BQMVs0DrmxwVKTtcBj3KGSxlArhWF/cQgQhFPnLsWu1BsSJWWP8uJ6g34oFrRIcps9SbmaVTvXq2aodGqbct51S7rf/TO0ucfXd3PyF4+jRxzy9hVl24nPVGc+S12Mjf+4l0m6WpT7WZ9Mdl7PXvGi4pJ7JmAAQhkM/8wsyLPriVdAxZ31DeryW90D75EP7n4sLtf27Y0bH9uxO8669ndDM6/EAenGOZFu5YJYMLo+JSlOdnMtDDpucwGmoBOSAv1XsSv0SaeE9mc6m8bUm4FCZvSIoAeTdRMIodhzixn+twuItVX/VOW2wXkTxJuJS9xXv4="

